version: 2
jobs:
  build:
    docker:
      - image: node:8.14-alpine

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run: yarn test:e2e
      - run: yarn test:unit
      - run: yarn build
      - save_cache:
        key: dt-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
            - dist
  deploy:
    working_directory: ~/repo
    docker:
      - image: node:8.14-alpine
    steps:
      - restore_cache:
          key: dt-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

